// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIbiMyp0DhAd03ABOC73eMsT80nh1iliU',
    appId: '1:456243166152:web:a46c8af2f31f8a803b1efd',
    messagingSenderId: '456243166152',
    projectId: 'flutter-content-2dc30',
    authDomain: 'flutter-content-2dc30.firebaseapp.com',
    storageBucket: 'flutter-content-2dc30.appspot.com',
    measurementId: 'G-VFNJ6G0KQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAo83txKJVQtaBqn-u0VJu_F-BxYdpRBM',
    appId: '1:456243166152:android:f9762a636e53bf583b1efd',
    messagingSenderId: '456243166152',
    projectId: 'flutter-content-2dc30',
    storageBucket: 'flutter-content-2dc30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgMLVPWn1lyPdBj-fzulI1LvwW0_YXPH4',
    appId: '1:456243166152:ios:9ca18d081ca26f3c3b1efd',
    messagingSenderId: '456243166152',
    projectId: 'flutter-content-2dc30',
    storageBucket: 'flutter-content-2dc30.appspot.com',
    iosClientId: '456243166152-2lmtnfrbsvv9mddr8knge7hi64hfolta.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgMLVPWn1lyPdBj-fzulI1LvwW0_YXPH4',
    appId: '1:456243166152:ios:c72d1aa821d16d9e3b1efd',
    messagingSenderId: '456243166152',
    projectId: 'flutter-content-2dc30',
    storageBucket: 'flutter-content-2dc30.appspot.com',
    iosClientId: '456243166152-07qmdqa9dln9bopvjh1p2ksubsvut277.apps.googleusercontent.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
