// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class Algc_DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56hK9hq6vzBZqRhSfVq8whbR6JBCVM_U',
    appId: '1:625609945831:web:0f684576c3318157d76842',
    messagingSenderId: '625609945831',
    projectId: 'flowchart-studio',
    authDomain: 'flowchart-studio.firebaseapp.com',
    storageBucket: 'flowchart-studio.appspot.com',
    measurementId: 'G-514HRBVZSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5GKyYakzp7OySem3uIok_jrMAMQo1TYM',
    appId: '1:625609945831:android:cb1ab658551684efd76842',
    messagingSenderId: '625609945831',
    projectId: 'flowchart-studio',
    storageBucket: 'flowchart-studio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGzEN9dQ7HZEEUKQEN4FkUBK5k_4Q4WDQ',
    appId: '1:625609945831:ios:5485f8b174d17815d76842',
    messagingSenderId: '625609945831',
    projectId: 'flowchart-studio',
    storageBucket: 'flowchart-studio.appspot.com',
    androidClientId: '625609945831-lp184bmrohmbqjqag22l6hn63neivu8q.apps.googleusercontent.com',
    iosClientId: '625609945831-3s0io870vcu3l6jpk22om5no3mdpv384.apps.googleusercontent.com',
    iosBundleId: 'app.algc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGzEN9dQ7HZEEUKQEN4FkUBK5k_4Q4WDQ',
    appId: '1:625609945831:ios:5485f8b174d17815d76842',
    messagingSenderId: '625609945831',
    projectId: 'flowchart-studio',
    storageBucket: 'flowchart-studio.appspot.com',
    androidClientId: '625609945831-lp184bmrohmbqjqag22l6hn63neivu8q.apps.googleusercontent.com',
    iosClientId: '625609945831-3s0io870vcu3l6jpk22om5no3mdpv384.apps.googleusercontent.com',
    iosBundleId: 'app.algc',
  );
}
