// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class BH_DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRBmoKWr1PRXvDdAfCC2ei_2aQBQ8iSCQ',
    appId: '1:188627927914:web:2b6ed1262bffb562ed1b13',
    messagingSenderId: '188627927914',
    projectId: 'bh-apps',
    authDomain: 'bh-apps.firebaseapp.com',
    storageBucket: 'bh-apps.appspot.com',
    measurementId: 'G-1YWEKWGGBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUYK3eFO2aCKWZ-7oKaKRNCx5fO5Z74g',
    appId: '1:188627927914:android:3099b9fa05ea596ced1b13',
    messagingSenderId: '188627927914',
    projectId: 'bh-apps',
    storageBucket: 'bh-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGMtpWEloPNaeGIG1f-Dh4RBWGf5CTmmI',
    appId: '1:188627927914:ios:722d3717dd0a9b18ed1b13',
    messagingSenderId: '188627927914',
    projectId: 'bh-apps',
    storageBucket: 'bh-apps.appspot.com',
    iosBundleId: 'com.example.mysample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGMtpWEloPNaeGIG1f-Dh4RBWGf5CTmmI',
    appId: '1:188627927914:ios:722d3717dd0a9b18ed1b13',
    messagingSenderId: '188627927914',
    projectId: 'bh-apps',
    storageBucket: 'bh-apps.appspot.com',
    iosBundleId: 'com.example.mysample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRBmoKWr1PRXvDdAfCC2ei_2aQBQ8iSCQ',
    appId: '1:188627927914:web:6818520532c7cb2aed1b13',
    messagingSenderId: '188627927914',
    projectId: 'bh-apps',
    authDomain: 'bh-apps.firebaseapp.com',
    storageBucket: 'bh-apps.appspot.com',
    measurementId: 'G-JVSWWXS7N6',
  );

}