@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Passwordless Sign In

participant User
participant "User's\nEmail\napp" as Gmail
participant "AlgC\n(sign in dlg)" as AlgC
participant "Cloud Run\n(gcr-bh-apps)" as CloudRun
participant ClickSend
database Firestore

activate User
activate AlgC

==auth dialog==

User->AlgC:enter\nemail \naddress


AlgC->CloudRun:<color #green>POST\n<color #blue>/sendSignInEmail</color>\n</color>{email address}

activate CloudRun

CloudRun->CloudRun:generate token with 5min expiry.\ngenerate email with a 'confirm'\nbutton linking to Cloud Run \n<color #blue>**/confirm/<token>**</color>


CloudRun->Firestore:save token to /unconfirmed-tokens

CloudRun->ClickSend:send email to user

CloudRun->AlgC:return token\nstatus 200

deactivate CloudRun

AlgC->User:show toast\n('go open your email')\n\n<color #purple>**keep dlg open**</color>

==open email and tap the <color #blue>**confirm**</color> button==

Create Gmail

User->Gmail:open email and\ntap the confirm\nbutton
activate Gmail


Gmail->CloudRun:<color #green>GET</color>\n<color #blue>/confirm</color>\n/<token>

deactivate Gmail
activate CloudRun

CloudRun->Firestore:remove token from /unconfirmed-tokens\nand add to /confirmed-tokens


deactivate CloudRun

==tap the <color #blue>**continue**</color> button==

User->AlgC:tap 'continue'
AlgC->Firestore:check token in /confirmed-tokens

AlgC->AlgC:if token found, save {confirmed: email address}\nin local storage and dismiss the sign in dlg

@enduml