@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Passwordless Sign In - User enters Email Address

participant User
participant "User's\nEmail\napp" as Gmail
participant "Sign in dlg" as sign_in_dlg
participant CAPIBloC as capiBloc
participant "Cloud Run\n(gcr-bh-apps)" as CloudRun
participant ClickSend
database Firestore

activate User

==auth dialog==

User->sign_in_dlg:enter\nemail \naddress

activate sign_in_dlg
sign_in_dlg->capiBloc:event: "signInRequested"
deactivate sign_in_dlg

activate capiBloc

capiBloc->CloudRun:<color #green>POST\n<color #blue>/sendSignInEmail</color>\n{email address}

activate CloudRun

CloudRun->CloudRun:generate token with 5min expiry.


CloudRun->Firestore:save token to /unconfirmed-tokens

CloudRun->ClickSend:generate email with a 'confirm'\nbutton linking to Cloud Run \n<color #blue>**/confirm/<token>**</color> and\nsend email to user via ClickSend

activate ClickSend
CloudRun->capiBloc:return token\nstatus 200
deactivate CloudRun

capiBloc->User:emit auth-status "emailedUserAConfirmButton"

deactivate capiBloc

ClickSend->User:email containing confirm button
deactivate ClickSend

@enduml