@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Passwordless Sign In - User open email and taps the <color #blue>**confirm**</color> button

participant User
participant GmailApp as Gmail
participant "Cloud Run\n(gcr-bh-apps)" as CloudRun
database Firestore

activate User


User->Gmail:open email and\ntap the confirm\nbutton
activate Gmail


Gmail->CloudRun:<color #green>GET</color>\n<color #blue>/confirm</color>\n/<token>

deactivate Gmail
activate CloudRun

CloudRun->Firestore:remove token\nfrom /unconfirmed-tokens\n\nadd to /confirmed-tokens

deactivate CloudRun

@enduml