name: fsdui_admin
description: Migration tool — clones /flutter-content/biancashouse to /flutter-content/biancashouse.com, removing SnippetRootNode and renaming deprecated node fields.
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

  fsdui:  #any
    path: ../../fsdui
    
flutter:
  uses-material-design: true