// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class BH_APPS_DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => web;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBstkoT5SGKl3sFnzlb0r1-v-Wqv6M3p3o",
    authDomain: "bh-apps.firebaseapp.com",
    projectId: "bh-apps",
    storageBucket: "bh-apps.appspot.com",
    messagingSenderId: "188627927914",
    appId: "1:188627927914:web:6d235164051f26d5ed1b13",
    measurementId: "G-L0D2E16T50",
  );
}